/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_accept[241] =
    {   0,
       54,   54,   59,   55,   54,   54,   54,   55,   23,   55,
       52,   55,   24,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   54,   54,    0,    0,    0,   56,
        0,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   18,   53,   53,   47,
       16,   53,   53,   53,   53,   53,   53,   19,   53,   21,
       17,   53,   53,   53,   53,   29,   53,   53,   27,   20,
       53,   22,   53,   53,   53,   53,    0,    0,   56,    0,
       53,   53,   30,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   12,   33,   53,   31,   53,
       53,   53,   13,   53,   35,   28,   53,   53,   53,   36,
       53,   53,   53,   53,   34,   42,    3,    0,    0,    0,
       53,   53,   53,   53,   53,   53,   26,   25,   53,   53,
       53,   53,   37,   53,   53,   53,   53,   53,    8,   53,
       53,   53,   53,   49,   53,   53,   53,    0,    0,   53,
       53,   38,    0,   32,   53,   53,   53,   53,   41,   44,
       53,   43,   39,   53,    0,   53,   53,   53,   53,   53,
        0,    0,   57,    0,   53,    0,   45,   53,   53,   53,
       51,    0,   15,    5,   48,   40,    9,   53,   14,    0,

        0,   53,   46,    6,   50,   53,    0,    0,    0,    0,
        4,   53,    0,    0,    0,    0,    7,    0,    0,    0,
        0,    0,    0,    0,   10,   11,    0,    0,    2,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    7,    1,    1,    1,    8,
        8,    8,    8,    8,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    8,    1,   13,
        1,   14,    8,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        1,    1,    1,    1,   42,    1,   41,   41,   41,   41,

       41,   41,   41,   43,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,    8,   41,    8,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    2,    2,    1,    2,    2,    1,    2,    1,    2,
        1,    3,    2,    2,    2,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    3,    4
    } ;

static yyconst short int yy_base[244] =
    {   0,
        0,    0,  599,  600,   42,   45,   48,   34,  600,  587,
      600,  588,  600,   42,   46,   44,   56,   43,   61,   66,
       45,   70,   81,  112,   53,   77,   85,   79,   98,  114,
       94,  110,  123,  102,  147,  155,  587,  575,  565,  583,
      583,  113,  118,  125,  141,  150,  149,  151,  134,  158,
      152,  161,  159,  163,  154,  169,  166,  186,  174,  167,
      177,  194,  198,  190,  201,  202,  203,  178,  206,  209,
      210,  215,  219,  213,  221,  217,  226,  227,  230,  234,
      246,  235,  248,  241,  252,  254,  570,  555,  579,  583,
      258,  263,  238,  269,  255,  277,  280,  283,  270,  286,

      289,  290,  294,  291,  297,  296,  301,  304,  302,  303,
      325,  312,  306,  328,  309,  317,  340,  337,  323,  330,
      343,  344,  348,  346,  351,  352,  600,  557,  581,  364,
      354,  359,  356,  364,  362,  371,  366,  368,  379,  385,
      387,  383,  388,  391,  390,  404,  402,  397,  403,  411,
      422,  405,  424,  406,  408,  425,  437,  552,  570,  428,
      439,  410,  553,  412,  443,  453,  456,  459,  446,  447,
      448,  461,  462,  463,  550,  474,  464,  468,  470,  471,
      549,  543,  600,  556,  479,  542,  475,  482,  480,  499,
      484,  554,  600,  490,  496,  502,  506,  507,  600,  540,

      545,  511,  600,  513,  515,  516,  544,  543,  539,  531,
      517,  519,  530,  529,  521,  519,  518,  517,  523,  517,
      515,  513,  526,  536,  600,  600,  251,  246,  600,  103,
      111,    0,  524,   62,  525,   95,   72,   44,  600,  600,
      565,  568,   59
    } ;

static yyconst short int yy_def[244] =
    {   0,
      240,    1,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  240,  240,  240,  240,  240,  240,
      240,  240,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  240,  240,  240,  242,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  240,  240,  242,  242,
      241,  241,  241,  240,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  240,
      241,  241,  241,  241,  241,  241,  240,  240,  240,  240,
      241,  241,  240,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  240,  240,  241,  241,  241,  241,  241,
      240,  240,  240,  240,  241,  240,  241,  241,  241,  241,
      241,  240,  240,  241,  241,  241,  241,  240,  240,  240,

      240,  241,  240,  241,  241,  241,  240,  240,  240,  240,
      241,  241,  240,  240,  240,  240,  241,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  243,  243,  240,  240,  240,  240,  240,  240,    0,
      240,  240,  240
    } ;

static yyconst short int yy_nxt[644] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,    4,    4,    4,
       10,   11,   12,    4,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   21,   33,   21,   34,   21,
       21,    4,   21,   35,   35,   35,   35,   35,   35,   35,
       35,   36,   38,   42,   42,   42,   42,   42,   44,   56,
       37,   47,  233,   39,   42,   48,   50,   42,   45,   49,
       46,   52,   42,   51,   57,   53,   58,   42,  239,   54,
       59,   42,   72,   42,   42,   42,   42,   42,   42,   63,
       42,   55,   42,  238,   42,   60,   42,   42,  237,   64,

       61,   62,   42,   65,  236,   42,   73,   42,   78,   42,
       66,   42,   74,   42,  232,   75,   83,   76,   42,   77,
       42,   42,   42,   42,   42,   42,   42,   67,   68,   42,
       80,   86,   79,   81,   42,   42,   42,  231,   85,   42,
       91,   69,   70,   42,   82,   42,   71,   84,   35,   35,
       35,   42,   42,   42,   42,   42,   35,   35,   36,   42,
       42,   42,   42,   42,   42,   42,   42,   37,   93,   42,
       42,   92,   42,   96,   42,   42,  100,   42,   42,   98,
       42,   94,   42,   95,  102,   42,  106,   97,   42,   42,
       42,   42,   42,   42,   99,   42,  101,   42,  103,   42,

       42,   42,   42,  104,   42,   42,  105,   42,   42,   42,
       42,  109,   42,   42,   42,   42,  110,   42,   42,   42,
       42,   42,  107,  108,   42,  113,   42,   42,   42,  111,
       42,   42,   42,  115,  114,   42,  112,   42,   42,   42,
      117,   42,   42,   42,   42,   42,   42,   42,  119,   42,
       42,   42,   42,  116,   42,  118,   42,   42,   42,   42,
       42,  121,   42,   42,  120,   42,   42,   42,   42,   42,
      124,   42,  230,  125,   42,   42,   42,  122,  229,   42,
       42,   42,   42,  123,  133,  132,  126,   42,   42,   42,
      131,   42,  138,   42,   42,   42,  134,   42,  137,   42,

       42,   42,   42,  136,   42,   42,  135,   42,   42,  139,
       42,   42,   42,   42,   42,   42,  141,   42,   42,  140,
       42,   42,  142,   42,   42,  143,  144,   42,   42,  146,
       42,   42,   42,  145,   42,   42,   42,   42,   42,   42,
      147,   42,   42,   42,   42,   42,  148,   42,   42,  149,
       42,   42,  153,   42,   42,   42,  151,   42,  150,   42,
      152,  154,   42,   42,   42,   42,   42,   42,  130,   42,
       42,   42,  159,   42,  161,   42,  155,   42,   42,   42,
      156,   42,   42,  164,   42,   42,  163,  157,  165,   42,
       42,  162,   42,   42,   42,  160,   42,   42,   42,   42,

       42,   42,   42,   42,  169,   42,  166,   42,   42,   42,
      168,  167,   42,   42,   42,   42,   42,   42,  171,   42,
       42,   42,   42,   42,   42,  170,   42,  172,   42,   42,
      175,   42,   42,   42,  177,   42,   42,  173,  174,   42,
      178,  176,  179,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,  185,  181,   42,   42,   42,
      180,  184,  187,   42,   42,   42,   42,   42,  188,   42,
       42,  189,   42,   42,   42,   42,  190,  191,   42,   42,
       42,   42,   42,  196,   42,   42,   42,   42,   42,   42,
       42,   42,  195,   42,   42,   42,  192,   42,  202,  197,

       42,   42,   42,   42,   42,   42,  194,   42,  204,   42,
       42,   42,  198,   42,  206,   42,   42,   42,   42,  205,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,  208,  234,  234,  235,  235,   42,  217,  228,
       42,  227,  226,   42,  225,  211,  224,   42,   42,  223,
      212,  222,   42,  221,   42,  220,   42,   42,   42,   42,
       42,  219,  218,  216,  215,  235,  235,   43,   43,  129,
      129,  129,  214,  213,  210,  209,  207,  203,  201,  200,
      199,  193,  186,  183,  182,  130,  158,  130,   89,  128,
      127,   90,   89,   88,   87,   41,   41,   40,  240,    3,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240
    } ;

static yyconst short int yy_chk[644] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    6,    6,    6,    7,
        7,    7,    8,   14,   18,   16,   21,   15,   14,   18,
        7,   15,  243,    8,   25,   15,   16,   17,   14,   15,
       14,   17,   19,   16,   18,   17,   19,   20,  238,   17,
       19,   22,   25,   14,   18,   16,   21,   15,   26,   22,
       28,   17,   23,  237,   25,   20,   27,   17,  236,   22,

       20,   20,   19,   23,  234,   31,   26,   20,   28,   29,
       23,   22,   26,   34,  231,   27,   31,   27,   26,   27,
       28,   32,   23,   24,   42,   30,   27,   24,   24,   43,
       30,   34,   29,   30,   33,   31,   44,  230,   33,   29,
       44,   24,   24,   34,   30,   49,   24,   32,   35,   35,
       35,   32,   45,   24,   42,   30,   36,   36,   36,   43,
       47,   46,   48,   51,   33,   55,   44,   36,   46,   50,
       53,   45,   52,   49,   54,   49,   53,   57,   60,   51,
       56,   47,   45,   48,   55,   59,   60,   50,   61,   68,
       47,   46,   48,   51,   52,   55,   54,   58,   56,   50,

       53,   64,   52,   58,   54,   62,   59,   57,   60,   63,
       56,   64,   65,   66,   67,   59,   65,   69,   61,   68,
       70,   71,   62,   63,   74,   69,   72,   58,   76,   66,
       73,   64,   75,   72,   69,   62,   67,   77,   78,   63,
       74,   79,   65,   66,   67,   80,   82,   69,   77,   93,
       70,   71,   84,   73,   74,   75,   72,   81,   76,   83,
       73,   81,   75,   85,   78,   86,   95,   77,   78,   91,
       84,   79,  228,   85,   92,   80,   82,   83,  227,   93,
       94,   99,   84,   83,   94,   92,   86,   81,   96,   83,
       91,   97,   99,   85,   98,   86,   95,  100,   98,   91,

      101,  102,  104,   97,   92,  103,   96,  106,  105,  100,
       94,   99,  107,  109,  110,  108,  102,  113,   96,  101,
      115,   97,  103,  112,   98,  104,  105,  100,  116,  110,
      101,  102,  104,  108,  119,  103,  111,  106,  105,  114,
      111,  120,  107,  109,  110,  108,  112,  113,  118,  114,
      115,  117,  119,  112,  121,  122,  117,  124,  116,  123,
      118,  121,  125,  126,  119,  131,  111,  133,  130,  114,
      132,  120,  130,  135,  132,  134,  122,  137,  118,  138,
      123,  117,  136,  135,  121,  122,  134,  124,  136,  123,
      139,  133,  125,  126,  142,  131,  140,  133,  141,  143,

      132,  145,  144,  135,  142,  134,  139,  137,  148,  138,
      141,  140,  136,  147,  149,  146,  152,  154,  145,  155,
      139,  162,  150,  164,  142,  144,  140,  146,  141,  143,
      150,  145,  144,  151,  152,  153,  156,  147,  148,  160,
      153,  151,  155,  147,  149,  146,  152,  154,  157,  155,
      161,  162,  150,  164,  165,  161,  157,  169,  170,  171,
      156,  160,  165,  151,  166,  153,  156,  167,  166,  160,
      168,  167,  172,  173,  174,  177,  168,  171,  157,  178,
      161,  179,  180,  178,  165,  176,  187,  169,  170,  171,
      185,  189,  177,  188,  166,  191,  174,  167,  185,  179,

      168,  194,  172,  173,  174,  177,  176,  195,  188,  178,
      190,  179,  180,  196,  190,  176,  187,  197,  198,  189,
      185,  189,  202,  188,  204,  191,  205,  206,  211,  217,
      212,  194,  198,  233,  235,  233,  235,  195,  212,  224,
      190,  223,  222,  196,  221,  202,  220,  197,  198,  219,
      206,  218,  202,  216,  204,  215,  205,  206,  211,  217,
      212,  214,  213,  210,  209,  233,  235,  241,  241,  242,
      242,  242,  208,  207,  201,  200,  192,  186,  184,  182,
      181,  175,  163,  159,  158,  129,  128,   90,   89,   88,
       87,   41,   40,   39,   38,   37,   12,   10,    3,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1807003.l"
#define INITIAL 0
#line 2 "1807003.l"
	#include<stdio.h>
	#include<string.h>
	#include "1807003.tab.h"

#line 589 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 "1807003.l"




#line 745 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 241 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 600 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 23 "1807003.l"
{return HEADER;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "1807003.l"
{return MAIN;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "1807003.l"
{return DEFINE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "1807003.l"
{return CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "1807003.l"
{return INT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 "1807003.l"
{return FLOAT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 "1807003.l"
{return DOUBLE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "1807003.l"
{return LONG;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "1807003.l"
{return IF;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "1807003.l"
{return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "1807003.l"
{return ELSE_IF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "1807003.l"
{return GOE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "1807003.l"
{return LOE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "1807003.l"
{return TWO_EQ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 44 "1807003.l"
{return NOT_EQ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 45 "1807003.l"
{return GT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 46 "1807003.l"
{return LT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 47 "1807003.l"
{return EQ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 48 "1807003.l"
{return LB;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 49 "1807003.l"
{return RB;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 50 "1807003.l"
{return LP;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "1807003.l"
{return RP;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "1807003.l"
{return END;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "1807003.l"
{return COL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "1807003.l"
{return DASH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "1807003.l"
{return COMA;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "1807003.l"
{return QT;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "1807003.l"
{return NOT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "1807003.l"
{return OR;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "1807003.l"
{return AND;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "1807003.l"
{return PLUS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "1807003.l"
{return MINUS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 65 "1807003.l"
{return MULT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "1807003.l"
{return DIV;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "1807003.l"
{return MOD;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "1807003.l"
{return POW;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "1807003.l"
{return FACT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "1807003.l"
{return INC;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "1807003.l"
{return DEC;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "1807003.l"
{return LOGICAL_OR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "1807003.l"
{return LOGICAL_AND;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "1807003.l"
{return XOR;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "1807003.l"
{return VOID;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "1807003.l"
{return RETURN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "1807003.l"
{return CASE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "1807003.l"
{return BREAK;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "1807003.l"
{return CONTINUE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "1807003.l"
{return SWITCH;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "1807003.l"
{return SCANF;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "1807003.l"
{return PRINTF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "1807003.l"
{return DEFAULT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "1807003.l"
{ yylval.number = atoi(yytext);
							return NUM;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "1807003.l"
{ yylval.string = strdup(yytext);
							return VAR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "1807003.l"

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "1807003.l"
{printf("%s --> invalid\n",yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "1807003.l"
{printf("single line comment\n");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "1807003.l"
{printf("multiple_line_comment\n");}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "1807003.l"
ECHO;
	YY_BREAK
#line 1120 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 241 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 241 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 240);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 96 "1807003.l"


int yywrap()
{
 return 1;
}

int main()
{

     freopen("input.txt","r",stdin);
	 freopen("output.txt","w",stdout);

	 yyparse();
    
	return 0;
}
